MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  LOF_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # LOF uses P5 instead of C5
  LOF:
    LOF_TOWER_BRANCH: "new" # new cls or bbox
    NUM_LOF: 1
    PULL_FACTOR: 1.
    PUSH_FACTOR: 1.
    USE_LOF: False
DATASETS:
#  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
#  TEST: ("coco_2014_minival",)
  TRAIN: ("coco_2017_train", )
  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  # IMS_PER_BATCH: 2
  WARMUP_METHOD: "constant"

